<table id="toolbox">

<tr id="itemtr">

<td name="speciationTd" id="itemtd" onmouseout="if (this.style.color != 'black') {this.style.opacity = 0.8;}" onmouseover="this.style.opacity = '1.0';" onclick="targetPath.hide();changeVisibilite2('poptaxa',0);tool='speciation';this.style.opacity=1.0;this.style.backgroundImage = 'url(img/white.png)';this.style.color = 'black';this.style.border = '4px solid #888888';document.getElementsByName('duplicationTd')[0].style.backgroundImage = 'url(img/menuback.png)';document.getElementsByName('duplicationTd')[0].style.color = 'white';document.getElementsByName('duplicationTd')[0].style.border = '2px outset white';document.getElementsByName('duplicationTd')[0].style.opacity = 0.8;document.getElementsByName('taxaTd')[0].style.backgroundImage = 'url(img/menuback.png)';document.getElementsByName('taxaTd')[0].style.color = 'white';document.getElementsByName('taxaTd')[0].style.border = '2px outset white';document.getElementsByName('taxaTd')[0].style.opacity = 0.8;document.getElementsByName('deleteTd')[0].style.backgroundImage = 'url(img/menuback.png)';document.getElementsByName('deleteTd')[0].style.color = 'white';document.getElementsByName('deleteTd')[0].style.border = '2px outset white';document.getElementsByName('deleteTd')[0].style.opacity = 0.8;document.getElementsByName('noDuplicationTd')[0].style.backgroundImage = 'url(img/menuback.png)';document.getElementsByName('noDuplicationTd')[0].style.color = 'white';document.getElementsByName('noDuplicationTd')[0].style.border = '2px outset white';document.getElementsByName('noDuplicationTd')[0].style.opacity = 0.8;document.getElementsByName('noSpeciationTd')[0].style.backgroundImage = 'url(img/menuback.png)';document.getElementsByName('noSpeciationTd')[0].style.color = 'white';document.getElementsByName('noSpeciationTd')[0].style.border = '2px outset white';document.getElementsByName('noSpeciationTd')[0].style.opacity = 0.8;" onmouseout="" onmouseover="">
<table id="organise"><tr><td><img height=20px src="img/speciation.png"></td><td>&nbsp;&nbsp;Speciation</td></tr></table>
</td>

<td name="duplicationTd" id="itemtd" onmouseout="if (this.style.color != 'black') {this.style.opacity = 0.8;}" onmouseover="this.style.opacity = '1.0';" onclick="targetPath.hide();changeVisibilite2('poptaxa',0);tool='duplication';this.style.opacity=1.0;this.style.backgroundImage = 'url(img/white.png)';this.style.color = 'black';this.style.border = '4px solid #888888';document.getElementsByName('speciationTd')[0].style.backgroundImage = 'url(img/menuback.png)';document.getElementsByName('speciationTd')[0].style.color = 'white';document.getElementsByName('speciationTd')[0].style.border = '2px outset white';document.getElementsByName('speciationTd')[0].style.opacity = 0.8;document.getElementsByName('taxaTd')[0].style.backgroundImage = 'url(img/menuback.png)';document.getElementsByName('taxaTd')[0].style.color = 'white';document.getElementsByName('taxaTd')[0].style.border = '2px outset white';document.getElementsByName('taxaTd')[0].style.opacity = 0.8;document.getElementsByName('deleteTd')[0].style.backgroundImage = 'url(img/menuback.png)';document.getElementsByName('deleteTd')[0].style.color = 'white';document.getElementsByName('deleteTd')[0].style.border = '2px outset white';document.getElementsByName('deleteTd')[0].style.opacity = 0.8;document.getElementsByName('noDuplicationTd')[0].style.backgroundImage = 'url(img/menuback.png)';document.getElementsByName('noDuplicationTd')[0].style.color = 'white';document.getElementsByName('noDuplicationTd')[0].style.border = '2px outset white';document.getElementsByName('noDuplicationTd')[0].style.opacity = 0.8;document.getElementsByName('noSpeciationTd')[0].style.backgroundImage = 'url(img/menuback.png)';document.getElementsByName('noSpeciationTd')[0].style.color = 'white';document.getElementsByName('noSpeciationTd')[0].style.border = '2px outset white';document.getElementsByName('noSpeciationTd')[0].style.opacity = 0.8;" onmouseout="" onmouseover="">
<table id="organise"><tr><td><img height=20px src="img/duplication.png"></td><td>&nbsp;&nbsp;Duplication</td></tr></table>
</td>

<td name="taxaTd" id="itemtd" onmouseout="if (this.style.color != 'black') {this.style.opacity = 0.8;}" onmouseover="this.style.opacity = '1.0';" onclick="tool='taxa';this.style.opacity=1.0;this.style.backgroundImage = 'url(img/white.png)';this.style.color = 'black';this.style.border = '4px solid #888888';document.getElementsByName('speciationTd')[0].style.backgroundImage = 'url(img/menuback.png)';document.getElementsByName('speciationTd')[0].style.color = 'white';document.getElementsByName('speciationTd')[0].style.border = '2px outset white';document.getElementsByName('speciationTd')[0].style.opacity = 0.8;document.getElementsByName('duplicationTd')[0].style.backgroundImage = 'url(img/menuback.png)';document.getElementsByName('duplicationTd')[0].style.color = 'white';document.getElementsByName('duplicationTd')[0].style.border = '2px outset white';document.getElementsByName('duplicationTd')[0].style.opacity = 0.8;document.getElementsByName('deleteTd')[0].style.backgroundImage = 'url(img/menuback.png)';document.getElementsByName('deleteTd')[0].style.color = 'white';document.getElementsByName('deleteTd')[0].style.border = '2px outset white';document.getElementsByName('deleteTd')[0].style.opacity = 0.8;document.getElementsByName('noDuplicationTd')[0].style.backgroundImage = 'url(img/menuback.png)';document.getElementsByName('noDuplicationTd')[0].style.color = 'white';document.getElementsByName('noDuplicationTd')[0].style.border = '2px outset white';document.getElementsByName('noDuplicationTd')[0].style.opacity = 0.8;document.getElementsByName('noSpeciationTd')[0].style.backgroundImage = 'url(img/menuback.png)';document.getElementsByName('noSpeciationTd')[0].style.color = 'white';document.getElementsByName('noSpeciationTd')[0].style.border = '2px outset white';document.getElementsByName('noSpeciationTd')[0].style.opacity = 0.8;" onmouseout="" onmouseover="">
<table id="organise"><tr><td><img height=20px src="img/taxa.png"></td><td>&nbsp;&nbsp;Taxa</td></tr></table>
</td>

<td name="deleteTd" id="itemtd" onmouseout="if (this.style.color != 'black') {this.style.opacity = 0.8;}" onmouseover="this.style.opacity = '1.0';" onclick="targetPath.hide();changeVisibilite2('poptaxa',0);tool='delete';this.style.opacity=1.0;this.style.backgroundImage = 'url(img/white.png)';this.style.color = 'black';this.style.border = '4px solid #888888';document.getElementsByName('speciationTd')[0].style.backgroundImage = 'url(img/menuback.png)';document.getElementsByName('speciationTd')[0].style.color = 'white';document.getElementsByName('speciationTd')[0].style.border = '2px outset white';document.getElementsByName('speciationTd')[0].style.opacity = 0.8;document.getElementsByName('duplicationTd')[0].style.backgroundImage = 'url(img/menuback.png)';document.getElementsByName('duplicationTd')[0].style.color = 'white';document.getElementsByName('duplicationTd')[0].style.border = '2px outset white';document.getElementsByName('duplicationTd')[0].style.opacity = 0.8;document.getElementsByName('taxaTd')[0].style.backgroundImage = 'url(img/menuback.png)';document.getElementsByName('taxaTd')[0].style.color = 'white';document.getElementsByName('taxaTd')[0].style.border = '2px outset white';document.getElementsByName('taxaTd')[0].style.opacity = 0.8;document.getElementsByName('noDuplicationTd')[0].style.backgroundImage = 'url(img/menuback.png)';document.getElementsByName('noDuplicationTd')[0].style.color = 'white';document.getElementsByName('noDuplicationTd')[0].style.border = '2px outset white';document.getElementsByName('noDuplicationTd')[0].style.opacity = 0.8;document.getElementsByName('noSpeciationTd')[0].style.backgroundImage = 'url(img/menuback.png)';document.getElementsByName('noSpeciationTd')[0].style.color = 'white';document.getElementsByName('noSpeciationTd')[0].style.border = '2px outset white';document.getElementsByName('noSpeciationTd')[0].style.opacity = 0.8;" onmouseout="" onmouseover="">
<table id="organise"><tr><td><img height=20px src="img/corbeille.png"></td><td>&nbsp;&nbsp;Delete</td></tr></table>
</td>

<td width="100%"></td>

</tr>

<script type="text/javascript">
document.getElementsByName('speciationTd')[0].style.backgroundImage = 'url(img/white.png)';
document.getElementsByName('speciationTd')[0].style.color = 'black';
document.getElementsByName('speciationTd')[0].style.border = '4px solid #888888';
document.getElementsByName('speciationTd')[0].style.opacity = 1.0;
</script>

</table>
<table id="toolbox">

<tr id="itemtr">

<td name="noDuplicationTd" id="itemtd" onmouseout="if (this.style.color != 'black') {this.style.opacity = 0.8;}" onmouseover="this.style.opacity = '1.0';" onclick="targetPath.hide();changeVisibilite2('poptaxa',0);tool='noDuplications';this.style.opacity=1.0;this.style.backgroundImage = 'url(img/white.png)';this.style.color = 'black';this.style.border = '4px solid #888888';document.getElementsByName('duplicationTd')[0].style.backgroundImage = 'url(img/menuback.png)';document.getElementsByName('duplicationTd')[0].style.color = 'white';document.getElementsByName('duplicationTd')[0].style.border = '2px outset white';document.getElementsByName('duplicationTd')[0].style.opacity = 0.8;document.getElementsByName('taxaTd')[0].style.backgroundImage = 'url(img/menuback.png)';document.getElementsByName('taxaTd')[0].style.color = 'white';document.getElementsByName('taxaTd')[0].style.border = '2px outset white';document.getElementsByName('taxaTd')[0].style.opacity = 0.8;document.getElementsByName('deleteTd')[0].style.backgroundImage = 'url(img/menuback.png)';document.getElementsByName('deleteTd')[0].style.color = 'white';document.getElementsByName('deleteTd')[0].style.border = '2px outset white';document.getElementsByName('deleteTd')[0].style.opacity = 0.8;document.getElementsByName('noSpeciationTd')[0].style.backgroundImage = 'url(img/menuback.png)';document.getElementsByName('noSpeciationTd')[0].style.color = 'white';document.getElementsByName('noSpeciationTd')[0].style.border = '2px outset white';document.getElementsByName('noSpeciationTd')[0].style.opacity = 0.8;document.getElementsByName('speciationTd')[0].style.backgroundImage = 'url(img/menuback.png)';document.getElementsByName('speciationTd')[0].style.color = 'white';document.getElementsByName('speciationTd')[0].style.border = '2px outset white';document.getElementsByName('speciationTd')[0].style.opacity = 0.8;" onmouseout="" onmouseover="">
<table id="organise"><tr><td><img height=20px src="img/speciation.png"></td><td>&nbsp;&nbsp;No duplications</td></tr></table>
</td>

<td name="noSpeciationTd" id="itemtd" onmouseout="if (this.style.color != 'black') {this.style.opacity = 0.8;}" onmouseover="this.style.opacity = '1.0';" onclick="targetPath.hide();changeVisibilite2('poptaxa',0);tool='noSpeciations';this.style.opacity=1.0;this.style.backgroundImage = 'url(img/white.png)';this.style.color = 'black';this.style.border = '4px solid #888888';document.getElementsByName('speciationTd')[0].style.backgroundImage = 'url(img/menuback.png)';document.getElementsByName('speciationTd')[0].style.color = 'white';document.getElementsByName('speciationTd')[0].style.border = '2px outset white';document.getElementsByName('speciationTd')[0].style.opacity = 0.8;document.getElementsByName('taxaTd')[0].style.backgroundImage = 'url(img/menuback.png)';document.getElementsByName('taxaTd')[0].style.color = 'white';document.getElementsByName('taxaTd')[0].style.border = '2px outset white';document.getElementsByName('taxaTd')[0].style.opacity = 0.8;document.getElementsByName('deleteTd')[0].style.backgroundImage = 'url(img/menuback.png)';document.getElementsByName('deleteTd')[0].style.color = 'white';document.getElementsByName('deleteTd')[0].style.border = '2px outset white';document.getElementsByName('deleteTd')[0].style.opacity = 0.8;document.getElementsByName('noDuplicationTd')[0].style.backgroundImage = 'url(img/menuback.png)';document.getElementsByName('noDuplicationTd')[0].style.color = 'white';document.getElementsByName('noDuplicationTd')[0].style.border = '2px outset white';document.getElementsByName('noDuplicationTd')[0].style.opacity = 0.8;document.getElementsByName('duplicationTd')[0].style.backgroundImage = 'url(img/menuback.png)';document.getElementsByName('duplicationTd')[0].style.color = 'white';document.getElementsByName('duplicationTd')[0].style.border = '2px outset white';document.getElementsByName('duplicationTd')[0].style.opacity = 0.8;" onmouseout="" onmouseover="">
<table id="organise"><tr><td><img height=20px src="img/duplication.png"></td><td>&nbsp;&nbsp;No speciations</td></tr></table>
</td>




<td width="100%"></td>

</tr>

</table>
