
<script type="text/javascript">
function getElementsByName_iefix(tag, name) {
	var elem=document.getElementsByTagName(tag);
	var arr=new Array();
	for(i=0,iarr=0; i < elem.length; i++) {
		att=elem[i].getAttribute("name");
		if(att == name) {
			arr[iarr]=elem[i];
			iarr++;
		}
	}
	return arr;
}
</script>

<table id="toolbox">

<tr id="itemtr">

<td name="speciationTd" id="itemtd" onmouseout="if (this.style.color != 'black') {this.style.opacity = 0.8;}" onmouseover="this.style.opacity = '1.0';" onclick="eraseTarget();changeVisibilite2('poptaxa',0);tool='speciation';this.style.opacity=1.0;this.style.backgroundImage = 'url(img/white.png)';this.style.color = 'black';this.style.border = '4px solid #888888';getElementsByName_iefix('td','duplicationTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','duplicationTd')[0].style.color = 'white';getElementsByName_iefix('td','duplicationTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','duplicationTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','taxaTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','taxaTd')[0].style.color = 'white';getElementsByName_iefix('td','taxaTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','taxaTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','deleteTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','deleteTd')[0].style.color = 'white';getElementsByName_iefix('td','deleteTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','deleteTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','noDuplicationTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','noDuplicationTd')[0].style.color = 'white';getElementsByName_iefix('td','noDuplicationTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','noDuplicationTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','noSpeciationTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','noSpeciationTd')[0].style.color = 'white';getElementsByName_iefix('td','noSpeciationTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','noSpeciationTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','noConstraintTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','noConstraintTd')[0].style.color = 'white';getElementsByName_iefix('td','noConstraintTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','noConstraintTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','transfertTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','transfertTd')[0].style.color = 'white';getElementsByName_iefix('td','transfertTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','transfertTd')[0].style.opacity = 0.8;" onmouseout="" onmouseover="">
<table id="organise"><tr><td><img height=20px src="img/speciation.png"></td><td>&nbsp;&nbsp;<?php if ($spec!="NR") { ?>Speciation<?php } else { ?>Node<?php } ?></td></tr></table>
</td>
<?php if ($spec!="NR") { ?>

<td name="duplicationTd" id="itemtd" onmouseout="if (this.style.color != 'black') {this.style.opacity = 0.8;}" onmouseover="this.style.opacity = '1.0';" onclick="eraseTarget();changeVisibilite2('poptaxa',0);tool='duplication';this.style.opacity=1.0;this.style.backgroundImage = 'url(img/white.png)';this.style.color = 'black';this.style.border = '4px solid #888888';getElementsByName_iefix('td','speciationTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','speciationTd')[0].style.color = 'white';getElementsByName_iefix('td','speciationTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','speciationTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','taxaTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','taxaTd')[0].style.color = 'white';getElementsByName_iefix('td','taxaTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','taxaTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','deleteTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','deleteTd')[0].style.color = 'white';getElementsByName_iefix('td','deleteTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','deleteTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','noDuplicationTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','noDuplicationTd')[0].style.color = 'white';getElementsByName_iefix('td','noDuplicationTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','noDuplicationTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','noSpeciationTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','noSpeciationTd')[0].style.color = 'white';getElementsByName_iefix('td','noSpeciationTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','noSpeciationTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','noConstraintTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','noConstraintTd')[0].style.color = 'white';getElementsByName_iefix('td','noConstraintTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','noConstraintTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','transfertTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','transfertTd')[0].style.color = 'white';getElementsByName_iefix('td','transfertTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','transfertTd')[0].style.opacity = 0.8;" onmouseout="" onmouseover="">
<table id="organise"><tr><td><img height=20px src="img/duplication.png"></td><td>&nbsp;&nbsp;Duplication</td></tr></table>
</td>

<?php } ?>

<?php if ($spec=="DTL") { ?>


<td name="transfertTd" id="itemtd" onmouseout="if (this.style.color != 'black') {this.style.opacity = 0.8;}" onmouseover="this.style.opacity = '1.0';" onclick="eraseTarget();changeVisibilite2('poptaxa',0);tool='transfert';this.style.opacity=1.0;this.style.backgroundImage = 'url(img/white.png)';this.style.color = 'black';this.style.border = '4px solid #888888';getElementsByName_iefix('td','speciationTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','speciationTd')[0].style.color = 'white';getElementsByName_iefix('td','speciationTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','speciationTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','taxaTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','taxaTd')[0].style.color = 'white';getElementsByName_iefix('td','taxaTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','taxaTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','deleteTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','deleteTd')[0].style.color = 'white';getElementsByName_iefix('td','deleteTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','deleteTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','noDuplicationTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','noDuplicationTd')[0].style.color = 'white';getElementsByName_iefix('td','noDuplicationTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','noDuplicationTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','noSpeciationTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','noSpeciationTd')[0].style.color = 'white';getElementsByName_iefix('td','noSpeciationTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','noSpeciationTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','noConstraintTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','noConstraintTd')[0].style.color = 'white';getElementsByName_iefix('td','noConstraintTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','noConstraintTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','duplicationTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','duplicationTd')[0].style.color = 'white';getElementsByName_iefix('td','duplicationTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','duplicationTd')[0].style.opacity = 0.8;">
<table id="organise"><tr><td><img height=20px src="img/transfert.png"></td><td>&nbsp;&nbsp;Transfer</td></tr></table>
</td>

<?php } ?>

<td name="taxaTd" id="itemtd" onmouseout="if (this.style.color != 'black') {this.style.opacity = 0.8;}" onmouseover="this.style.opacity = '1.0';" onclick="tool='taxa';this.style.opacity=1.0;this.style.backgroundImage = 'url(img/white.png)';this.style.color = 'black';this.style.border = '4px solid #888888';getElementsByName_iefix('td','speciationTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','speciationTd')[0].style.color = 'white';getElementsByName_iefix('td','speciationTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','speciationTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','duplicationTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','duplicationTd')[0].style.color = 'white';getElementsByName_iefix('td','duplicationTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','duplicationTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','deleteTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','deleteTd')[0].style.color = 'white';getElementsByName_iefix('td','deleteTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','deleteTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','noDuplicationTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','noDuplicationTd')[0].style.color = 'white';getElementsByName_iefix('td','noDuplicationTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','noDuplicationTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','noSpeciationTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','noSpeciationTd')[0].style.color = 'white';getElementsByName_iefix('td','noSpeciationTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','noSpeciationTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','noConstraintTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','noConstraintTd')[0].style.color = 'white';getElementsByName_iefix('td','noConstraintTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','noConstraintTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','transfertTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','transfertTd')[0].style.color = 'white';getElementsByName_iefix('td','transfertTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','transfertTd')[0].style.opacity = 0.8;" onmouseout="" onmouseover="">
<table id="organise"><tr><td><img height=20px src="img/taxa.png"></td><td>&nbsp;&nbsp;Taxa</td></tr></table>
</td>

<td name="deleteTd" id="itemtd" onmouseout="if (this.style.color != 'black') {this.style.opacity = 0.8;}" onmouseover="this.style.opacity = '1.0';" onclick="eraseTarget();changeVisibilite2('poptaxa',0);tool='delete';this.style.opacity=1.0;this.style.backgroundImage = 'url(img/white.png)';this.style.color = 'black';this.style.border = '4px solid #888888';getElementsByName_iefix('td','speciationTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','speciationTd')[0].style.color = 'white';getElementsByName_iefix('td','speciationTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','speciationTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','duplicationTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','duplicationTd')[0].style.color = 'white';getElementsByName_iefix('td','duplicationTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','duplicationTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','taxaTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','taxaTd')[0].style.color = 'white';getElementsByName_iefix('td','taxaTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','taxaTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','noDuplicationTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','noDuplicationTd')[0].style.color = 'white';getElementsByName_iefix('td','noDuplicationTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','noDuplicationTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','noSpeciationTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','noSpeciationTd')[0].style.color = 'white';getElementsByName_iefix('td','noSpeciationTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','noSpeciationTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','noConstraintTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','noConstraintTd')[0].style.color = 'white';getElementsByName_iefix('td','noConstraintTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','noConstraintTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','transfertTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','transfertTd')[0].style.color = 'white';getElementsByName_iefix('td','transfertTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','transfertTd')[0].style.opacity = 0.8;" onmouseout="" onmouseover="">
<table id="organise"><tr><td><img height=20px src="img/corbeille.png"></td><td>&nbsp;&nbsp;Delete</td></tr></table>
</td>




<td width="100%"></td>

</tr>

<script type="text/javascript">

getElementsByName_iefix('td','speciationTd')[0].style.backgroundImage = 'url(img/white.png)';
getElementsByName_iefix('td','speciationTd')[0].style.color = 'black';
getElementsByName_iefix('td','speciationTd')[0].style.border = '4px solid #888888';
getElementsByName_iefix('td','speciationTd')[0].style.opacity = 1.0;
</script>

</table>
<?php if ($spec!="NR") { ?>

<table id="toolbox">

<tr id="itemtr">

<td name="noDuplicationTd" id="itemtd" onmouseout="if (this.style.color != 'black') {this.style.opacity = 0.8;}" onmouseover="this.style.opacity = '1.0';" onclick="eraseTarget();changeVisibilite2('poptaxa',0);tool='noDuplications<?php if ($spec=="DTL") { ?>OrTransfers<?php } ?>';this.style.opacity=1.0;this.style.backgroundImage = 'url(img/white.png)';this.style.color = 'black';this.style.border = '4px solid #888888';getElementsByName_iefix('td','duplicationTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','duplicationTd')[0].style.color = 'white';getElementsByName_iefix('td','duplicationTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','duplicationTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','taxaTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','taxaTd')[0].style.color = 'white';getElementsByName_iefix('td','taxaTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','taxaTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','deleteTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','deleteTd')[0].style.color = 'white';getElementsByName_iefix('td','deleteTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','deleteTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','noSpeciationTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','noSpeciationTd')[0].style.color = 'white';getElementsByName_iefix('td','noSpeciationTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','noSpeciationTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','speciationTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','speciationTd')[0].style.color = 'white';getElementsByName_iefix('td','speciationTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','speciationTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','noConstraintTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','noConstraintTd')[0].style.color = 'white';getElementsByName_iefix('td','noConstraintTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','noConstraintTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','transfertTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','transfertTd')[0].style.color = 'white';getElementsByName_iefix('td','transfertTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','transfertTd')[0].style.opacity = 0.8;" onmouseout="" onmouseover="">
<table id="organise"><tr><td><img height=20px src="img/noDuplications.png"></td><td>&nbsp;&nbsp;No duplications<?php if ($spec=="DTL") { ?> or transfers<?php } ?></td></tr></table>
</td>

<td name="noSpeciationTd" id="itemtd" onmouseout="if (this.style.color != 'black') {this.style.opacity = 0.8;}" onmouseover="this.style.opacity = '1.0';" onclick="eraseTarget();changeVisibilite2('poptaxa',0);tool='noSpeciations';this.style.opacity=1.0;this.style.backgroundImage = 'url(img/white.png)';this.style.color = 'black';this.style.border = '4px solid #888888';getElementsByName_iefix('td','speciationTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','speciationTd')[0].style.color = 'white';getElementsByName_iefix('td','speciationTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','speciationTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','taxaTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','taxaTd')[0].style.color = 'white';getElementsByName_iefix('td','taxaTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','taxaTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','deleteTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','deleteTd')[0].style.color = 'white';getElementsByName_iefix('td','deleteTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','deleteTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','noDuplicationTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','noDuplicationTd')[0].style.color = 'white';getElementsByName_iefix('td','noDuplicationTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','noDuplicationTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','duplicationTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','duplicationTd')[0].style.color = 'white';getElementsByName_iefix('td','duplicationTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','duplicationTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','noConstraintTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','noConstraintTd')[0].style.color = 'white';getElementsByName_iefix('td','noConstraintTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','noConstraintTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','transfertTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','transfertTd')[0].style.color = 'white';getElementsByName_iefix('td','transfertTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','transfertTd')[0].style.opacity = 0.8;" onmouseout="" onmouseover="">
<table id="organise"><tr><td><img height=20px src="img/noSpeciations.png"></td><td>&nbsp;&nbsp;No speciations</td></tr></table>
</td>

<td name="noConstraintTd" id="itemtd" onmouseout="if (this.style.color != 'black') {this.style.opacity = 0.8;}" onmouseover="this.style.opacity = '1.0';" onclick="eraseTarget();changeVisibilite2('poptaxa',0);tool='noConstraints';this.style.opacity=1.0;this.style.backgroundImage = 'url(img/white.png)';this.style.color = 'black';this.style.border = '4px solid #888888';getElementsByName_iefix('td','duplicationTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','duplicationTd')[0].style.color = 'white';getElementsByName_iefix('td','duplicationTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','duplicationTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','taxaTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','taxaTd')[0].style.color = 'white';getElementsByName_iefix('td','taxaTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','taxaTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','deleteTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','deleteTd')[0].style.color = 'white';getElementsByName_iefix('td','deleteTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','deleteTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','noSpeciationTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','noSpeciationTd')[0].style.color = 'white';getElementsByName_iefix('td','noSpeciationTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','noSpeciationTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','speciationTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','speciationTd')[0].style.color = 'white';getElementsByName_iefix('td','speciationTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','speciationTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','noDuplicationTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','noDuplicationTd')[0].style.color = 'white';getElementsByName_iefix('td','noDuplicationTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','noDuplicationTd')[0].style.opacity = 0.8;getElementsByName_iefix('td','transfertTd')[0].style.backgroundImage = 'url(img/menuback.png)';getElementsByName_iefix('td','transfertTd')[0].style.color = 'white';getElementsByName_iefix('td','transfertTd')[0].style.border = '2px outset white';getElementsByName_iefix('td','transfertTd')[0].style.opacity = 0.8;" onmouseout="" onmouseover="">
<table id="organise"><tr><td><img height=20px src="img/noConstraints.png"></td><td>&nbsp;&nbsp;No constraints</td></tr></table>
</td>


<td width="100%"></td>

</tr>

</table>

<?php } ?>